// Purpose: Move inline scripts out of HTML into a module. This file is loaded by index.html
// and performs lightweight client bootstrap tasks (dev API base and a narrow unhandledrejection suppression).

// Only adjust the manifest href when it's a relative path (avoid converting already-absolute URLs).
if (typeof window !== 'undefined')
{
    if (location.hostname === 'localhost' || location.hostname === '127.0.0.1') {
        window.__API_BASE__ = `${location.protocol}//${location.hostname}:3000`;
    }

    try {
        const manifestLink = document.querySelector('link[rel="manifest"]');
        if (manifestLink && window.__API_BASE__) {
            const hrefAttr = manifestLink.getAttribute('href') || '';
            // Only rewrite when href is relative (doesn't start with http(s):// or //)
            if (!/^(https?:)?\/\//.test(hrefAttr)) {
                const base = String(window.__API_BASE__).replace(/\/$/, '');
                manifestLink.href = `${base}/${hrefAttr.replace(/^\.\/|^\//, '')}`;
                manifestLink.setAttribute('href', manifestLink.href);
                console.debug('Manifest href adjusted to', manifestLink.href);
            } else {
                console.debug('Manifest href is absolute, skipping adjustment:', hrefAttr);
            }
        }
    } catch (e) {
        console.warn('Could not adjust manifest href:', e);
    }

    // Defensive: suppress noisy unhandled promise rejections generated by injected extensions/preview scripts
    // when they indicate an asynchronous response by returning true but never reply. This is not an app bug;
    // it's caused by external tooling (browser extension / IDE preview). We only suppress the specific message
    // to avoid masking other real errors.
    window.addEventListener('unhandledrejection', (event) => {
        try {
            const reason = event.reason;
            const msg = reason && reason.message ? String(reason.message) : String(reason);
            if (typeof msg === 'string' && msg.includes('A listener indicated an asynchronous response')) {
                // Prevent the default logging of this unhelpful extension/preview error
                event.preventDefault();
                // Keep a quiet debug log so developers can still see the occurrence in devtools if needed
                console.debug('Suppressed noisy extension/unhandledrejection:', msg);
            }
        } catch (e) {
            // If our suppression logic fails, don't interfere with normal error handling
            console.error('Error in unhandledrejection suppression handler', e);
        }
    });
}